FROM golang:1.17-alpine3.16 as build

# Install the Protocol Buffers compiler and Go plugin
RUN apk add protobuf git make zip
RUN go get github.com/golang/protobuf/protoc-gen-go \
    google.golang.org/grpc/cmd/protoc-gen-go-grpc

# Create the source folder
RUN mkdir /go/plugin
WORKDIR /go/plugin

# Copy the source to the build folder
COPY . /go/plugin

# Build the plugin
RUN chmod +x ./print_arch
RUN protoc -I thirdparty/proto -I . --go_out=plugins=grpc:. --go_opt=paths=source_relative ./platform/output.proto \
    && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /go/plugin/bin/waypoint-plugin-nomad-pack /go/plugin/main.go

# TODO: Use Waypoint to build this image, and template the base image
# and tag for Nomad Pack
FROM hashicorp/nomad-pack:0.0.1-techpreview.3 AS builder

FROM paladindevops/waypoint-odr-alpine:latest

# Git CLI is required for Nomad Pack
RUN apk add --no-cache git

COPY --from=builder /bin/nomad-pack /kaniko/nomad-pack
COPY --from=build /go/plugin/bin/waypoint-plugin-nomad-pack /root/.config/waypoint/plugins/waypoint-plugin-nomad-pack
