# TODO: Use Waypoint to build this image, and template the base image
# and tag for Nomad Pack
FROM hashicorp/nomad-pack:0.0.1-techpreview.3 AS builder

FROM hashicorp/waypoint-odr:latest

COPY --from=builder /bin/nomad-pack /usr/local/bin/nomad-pack

